//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AQC_Manager {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class allSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static allSettings defaultInstance = ((allSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new allSettings())));
        
        public static allSettings Default {
            get {
                return defaultInstance;
            }
        }
    }
}
